### ISSUE TITLE
[FEATURE]doesnt work with phobos and clients

### ISSUE THREAD

**Issue by XdFag** [Nooniboi/Xannax-master#1]
**Is your feature request related to a problem? Please describe.**
It Doesnt Work With Phobos

**Describe the solution you'd like**
Make it compatibile with phobos

**Describe alternatives you've considered**
idk

**Additional context**
what do i put here

**Comment by Nooniboi** [comment]
XannaX has many compatibility issues with certain clients however im not here to update this client i simply leaked the client with the latest version and source //Noon

**Comment by 0yq** [comment]
dum
